spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciador_db
spring.datasource.username=postgres
spring.datasource.password=sua_senha_aqui
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
